# Generated by Django 4.2.9 on 2026-04-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('green_votes', models.PositiveIntegerField(default=0)),
                ('yellow_votes', models.PositiveIntegerField(default=0)),
                ('red_votes', models.PositiveIntegerField(default=0)),
                ('dominant', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red'), ('none', 'No data')], default='none', max_length=10)),
                ('start_lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('start_lng', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('end_lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('end_lng', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
