# Generated by Django 4.2.9 on 2026-04-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='detail',
            field=models.TextField(blank=True, help_text='Reason / extra context, e.g. ban reason'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_type',
            field=models.CharField(blank=True, help_text="e.g. 'POI', 'User', 'Segment'", max_length=32),
        ),
    ]
