# Generated by Django 4.2.9 on 2026-05-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='geometry',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
